### ISSUE TITLE
http://reactivex.io/documentation/operators.html "mapTo" points to "map"

### ISSUE THREAD

**Issue by jverkoey** [ReactiveX/reactivex.github.io#342]
It seems that `mapTo` has a specific meaning in the rxjs docs: http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-mapTo but the reactivex docs links to the `map` operator. Should there be a specific `mapTo` page in the reactivex docs?

**Comment by DavidMGross** [comment]
I think the Map page is a good place to describe the `mapTo` operator. The web pages group operators that have similar functions, and `mapTo` is similar enough to `map` that it makes sense for them to be described in the same place.

I note that currently there's no entry for `mapTo` in the RxJS accordion on the Map page, though, so that needs fixing. (Though, as per #247, we'll probably end up just referring people to the more-maintained RxJS docs.)
