### ISSUE TITLE
switchMap documentation direct to flatMap

### ISSUE THREAD

**Issue by saikatbhadra** [ReactiveX/reactivex.github.io#352]
In `https://github.com/ReactiveX/reactivex.github.io/blob/develop/documentation/operators.markdown` we seem to have a typo where the documentation link for switchMap directs to a similar (but different) operator:

* [`switchMap`]({{ site.url }}/documentation/operators/flatmap.html)

`switchMap` has a subtle change from flatmap so I think it is confusing to users that you are redirecting to a different (but similar) operator.

**Comment by DavidMGross** [comment]
The `switchMap` operator is documented on the `flatMap` page (along with `concatMap`, `selectMany`, `concat_all`, and several others with similar functions -- even StringObservable's `split`):

http://reactivex.io/documentation/operators/flatmap.html

Rather than having a documentation page for every operator, we have chosen to group operators with similar functions into a single documentation page so that it's easier for people to choose the operator that's most appropriate to their use case.

**Comment by saikatbhadra** [comment]
Ah ok - I didn't get this when I first skimmed the page because of the heading on the page/

However, I'm still a bit confused - in the language specific information section there is no mention of switchMap in the RxJS section. This made me believe switchMap wasn't supported. I also had trouble understanding what switchMap does as it's not explained in any section except the RxGroovy.

So a couple of questions:

1. Why is switchMap omitted from the RxJS section? Reading that made me think the function is not supported
2. Why is the switchMap explanation collapsed into the RxGroovy section but not the other sections. How is a user supposed to know where to find the function explanation without expanding each language section mentioning switchMap?

Thanks!

**Comment by DavidMGross** [comment]
The RxJS documentation on reactivex.github.io is out-of-date (see #247 ). This may also be true for some other languages. In general, documentation for RxJava and its derivatives is more extensive than for some other languages' variants, just because nobody has yet stepped forward to take charge of the documentation for those variants.
