### ISSUE TITLE
Interactive (RxMarbles) diagrams don't render in Safari

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/reactivex.github.io#88]
I tested the new embedded RxMarbles diagrams in Chrome, Firefox, and Safari 7.1.3, and while they seem to work in the first two, they don't render at all in Safari.

When I view-source, the RxMarbles line is &lt;rx-marbles key="foo"&gt;&lt;/rx-marbles&gt;... that is, unchanged from the static source.

There's a javascript error that only seems to show up in Safari ("TypeError: Attempted to assign to readonly property." at patches-mdv.js, line 57)... not sure if that would have anything to do with it (that error also turns up on pages that don't have embedded RxMarbles diagrams). I don't see any other javascript errors or warnings.

**Comment by staltz** [comment]
*Sigh* I tested in Chrome, Firefox, Opera, and IE, and somehow forgot about the existence of Safari. I'll look into it.

**Comment by staltz** [comment]
So it was actually not my new code that was breaking RxMarbles on Safari, that `TypeError` was *already* happening before RxMarbles was inserted. That was because of Polymer as a dependency is breaking in Safari. I just removed Polymer in PR #89 , and this error is a known issue to be fixed in Safari, not in Polymer: http://stackoverflow.com/questions/24432798/polymer-project-objects-not-rendering-in-os-x-10-10

**Comment by DavidMGross** [comment]
Looks good to me.

**Comment by DavidMGross** [comment]
And... we're live: http://reactivex.io/documentation/operators/combinelatest.html

Great work!
